### ISSUE TITLE
Nuget?

### ISSUE THREAD

**Issue by turowicz** [OrleansContrib/OrleansCassandraUtils#2]
@Arshia001 @sergeybykov is there a working Nuget package for Cassandra Persistance?

**Comment by sergeybykov** [comment]
I doubt it.

**Comment by Arshia001** [comment]
Remember I said there wasn't much to add? Forget that. Nuget package incoming.

**Comment by turowicz** [comment]
Would be great to test with Orleans 3.x

**Comment by Arshia001** [comment]
I've been running it in production with Orleans 3.x for quite some time now. Just let me get the code in shape real quick.

**Comment by turowicz** [comment]
@Arshia001 if you start by making it a Nuget package then you will be able to maintain the code whenever and just increment the package version each time you change something 😉

**Comment by Arshia001** [comment]
Yes, I know how that works.

**Comment by Arshia001** [comment]
Here you are: https://www.nuget.org/packages/Orleans.CassandraUtils/1.0.0

Turns out I've been maintaining a private copy of this code. There are relatively few changes as you can see, but I had a good laugh when I realized the project file in this repo was targeting .Net framework... anyway, that's all fixed now.

As I said, I've been using this code in production for quite some time now, so it should be stable. There may be edge-cases I haven't run into though, so don't just take my word for it.

**Comment by turowicz** [comment]
Thank you so much!
